In [1]:
#import libraries
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import seaborn as sns
import io
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from scipy import stats
import numpy as np

Mounted at /content/drive

In [11]:
#Read the dataset from drive
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/NEURAL NETWORKS/Churn_Modelling.csv',index_col="RowNumber")
dataset.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [12]:
# Finding Missing Values
print(dataset.isnull().sum())

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [13]:
#Handling Missing Values
dataset=dataset.drop(['Surname', 'Geography','Gender'], axis=1)

In [14]:
#Check for Duplicates
dataset.duplicated().sum()

0

In [15]:
#Normalize the dataset
scaler=StandardScaler()
dataset=pd.DataFrame(scaler.fit_transform(dataset))
dataset.head()

,0,1,2,3,4,5,6,7,8,9
0,-0.783213,-0.326221,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886,1.977165
1,-0.606534,-0.440036,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534,-0.505775
2,-0.995885,-1.536794,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687,1.977165
3,0.144767,0.501521,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918,-0.505775
4,0.652659,2.063884,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276,-0.505775

In [16]:
#split the dataset into input and output
X,Y=dataset.iloc[:,:-1].values ,dataset.iloc[:,-1].values
print('Input:\n',X,'\nOutput:\n',Y)

Input:
 [[-0.78321342 -0.32622142  0.29351742 ...  0.64609167  0.97024255
   0.02188649]
 [-0.60653412 -0.44003595  0.19816383 ... -1.54776799  0.97024255
   0.21653375]
 [-0.99588476 -1.53679418  0.29351742 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [-1.47928179  0.60498839 -0.27860412 ... -1.54776799  0.97024255
  -1.00864308]
 [-0.11935577  1.25683526  0.29351742 ...  0.64609167 -1.03067011
  -0.12523071]
 [-0.87055909  1.46377078 -1.04143285 ...  0.64609167 -1.03067011
  -1.07636976]]
Output:
 [ 1.97716468 -0.50577476  1.97716468 ...  1.97716468  1.97716468
 -0.50577476]

In [17]:

#splitting the data for training & Testing
Xtrain,Xtest,Ytrain,Ytest = train_test_split(X, Y, test_size=0.2)
print("Xtrain:" ,len(Xtrain), "\nXtest:", len(Xtest))
print("\nYtrain:" ,len(Ytrain), "\nYtest:", len(Ytest))

Xtrain: 8000
Xtest: 2000

Ytrain: 8000
Ytest: 2000